/** */
package it.toscana.regione.wsods.type;

import it.toscana.regione.wsods.exception.ConvertitoreException;


/**
 * @author cciurli
 *
 */
public enum Code {

	GENERICO(1000L,"1000 - Errore Generico"),
	PARAMETRO_NULLO(1001L,"1001 - Parametro nullo"),
	PARSER(1002L,"1002 - Errore di parser di un dato"),
	FORMATO(1003L,"1003 - Errore nel formato di un dato"),
	NAMBER_FORMAT(1004L,"1004 - impossibile parsare l'oggetto in un numero"),
	TIPO_INATTESO(1005L,"1005 - tipo inatteso"),
	NULL_INATTESSO(1006L,"1006 - Object nullo inatteso"),
	DATO_MANCANTE(1007L,"1007 - dato obbilgatorio assente"),
	UNKNOWN_TYPE(1008L,"1008 - cercato di ottenere un enumeratore con una chiave non rappresentata"),
	DATO_INCONGRUO(1009L,"1009 - un dato impiegato non e' congruo"),
	
	DAO_GENERICO(1100L,"1100 - Errore Generico su DAO"),
	DAO_ENTITY_MANAGER(1101L,"1101 - l'entity manager non e' inizzializzato correttamente"),
	DAO_CREATE_QUERY(1102L,"1102 - Non e' stato possibile crerare la Query"),
	DAO_PARAMETRO(1103L,"1103 - Un Parametro Atteso e' nullo o assente"),
	DAO_EXECUTE_UPDATE(1104L,"1104 - Non e' stato possibile eseguire la query in scrittura (INSERT/DELETE/UPDATE)"),
	DAO_EXECUTE_SELECT(1105L,"1105 - Non e' stato possibile eseguire la query in lettura (SELECT)"),
	DAO_RISULTATO_INATTESO(1106L,"1106 - si e' ottenuto un risultato in atteso"), 
	DAO_ENTITY_MANAGER_PERSIST(1107L,"1107 - la persist sul l'entity manager non e' terminata correttamente"),
	
	EJB_GENERICO(1200L,"1200 - Errore Generico su EJB"), 
	EJB_LOOKUP(1201L,"1201 - impossibile effettuare la lookup del EJB"), 
	EJB_POST_CONSTRUCT(1202L,"1202 - problemi durante la post constructi su EJB"), 
	EJB_PRE_DESTROY(1203L,"1203 - problemi durante la pre destroy su EJB"), 
	
	SDM_GENERICO(2000L,"2000 - Errore Generico su Sis Data Manager"), 
	SDM_SERVIZIO_NON_DISPONIBILE(2001L,"2001 - Servizio Sis Data Manager non disponibile"),
	SDM_PARSE_RESPONSE(2002L,"2002 - Errore Generico su Sis Data Manager"), 
	SDM_SOGGETTO_NON_TROVATO(2003L,"2003 - Sis Data Manager non ha reperito il soggetto cercato"), 
	SDM_DATI_OTTENUTI_NON_SUFFICIENTI(2004L,"2004 - Dati ottenuti dal servizio Sis Data Manager non sufficenti"),
	SDM_SERVIZIO_RESTITUISCE_UN_FAULT(2005L,"2005 - Servizio Sis Data Manager ha restituito un fault"),
	SDM_SERVIZIO_RESTITUISCE_ERRORE(2006L,"2006 - Servizio Sis Data Manager ha restituito un errore noto"),
	SDM_CODICE_FISCALE_VUOTO(2007L,"2007 - Codice Fiscale in ingresso a Sis Data Manager vuoto"),
	SDM_ID_UNIVERSALE_VUOTO(2008L,"2008 - Id Universale in ingresso a Sis Data Manager vuoto"),
	SDM_DATO_MANCANTE(2009L,"2009 - dati in ingresso non suffiscenti ad invocare Sis Data Manager"),
	SDM_SOGGETTO_NON_TROVATO_O_CON_TRATTI_PARZIALI_O_DATI_INPUT_MANCANTI(2010L,"2010 - Sis Data Manager non ha reperito il soggetto cercato oppure il soggetto reprito possiede tratti parziali oppure dati in ingresso non suffiscenti ad invocare Sis Data Manager"),
	SDM_GIANOV4_RISPONDE_CON_WARNING(2011L,"2011 - Il servizio REST ricercaAnagrafiche di GIANOV4 ha risposto con un WARNING"),
	SDM_GIANOV4_RISPONDE_CON_ERRORE(2012L,"2012 - Il servizio REST ricercaAnagrafiche di GIANOV4 ha risposto con ERRORE"),
	SDM_GIANOV4_NON_TROVA_ANAGRAFICHE(2013L,"2013 - Il servizio REST ricercaAnagrafiche di GIANOV4 non ha trovato anagrafiche"),
	SDM_GIANOV4_RITORNA_N_ANAGRAFICHE(2014L,"2014 - Il servizio REST ricercaAnagrafiche di GIANOV4 ha trovato N anagrafiche"),
	
	
	TRANSFORM_GENERICO(1400L,"1400 - Errore Generico sul Transformer"), 
	TRANSFORM_MARSCHALLER(1402L,"1402 - Impossibile effettuare il marshaller del messaggio"),
	TRANSFORM_UNMARSCHALLER(1403L,"1403 - Impossibile effettuare il unmarshaller del messaggio"),
	
	SENDER_GENERICO(1500L,"1500 - Errore Generico sul Sender"), 
	SENDER_SERVIZIO_NON_DISPONIBILE(1501L,"1501 - servizio non disponibile"),
	SENDER_SOAP_FAULT(1502L,"1502 - ottenuto un soap fault  come risposta"),
	
	WS_GENERICO(1600L,"1600 - Errore Web Server Generico"),
	WS_OPERATION_NULL(1601L,"1601 - Operazione assente"),
	WS_OPERATION_UK(1602L,"1602 - Operazione non riconosciuta"),
	WS_BODY(1603L,"1603 - Impossibile estrarre il body dal soap message"),
	WS_SAVE(1604L,"1604 - Impossibile invocare il saveChanges() sul soap message"),

	FE_GENERICO(1700L,"1700 - Errore Generico sul FrontEnd"),
	FE_DICHIARANTE_MANCANTE(1701L,"1701 - dichiarante assente impossibile creare l'autocertificazione"),
	FE_TITOLARE_MANCANTE(1702L,"1702 - titolare assente impossibile creare l'autocertificazione"),
	FE_BENEFICIARIO_MANCANTE(1703L,"1703 - beneficiario assente impossibile creare l'autocertificazione"),
	FE_DICHIARAZIONE_MANCANTE(1704L,"1704 - dichiarazione assente impossibile creare l'autocertificazione"),
	FE_AUTOCERTIFICAZIONE_MANCANTE(1705L,"1705 - autocertificazione assente"),
	FE_USER_NESSUN_CF(1706L,"1706 - non si e' trovato nessun fc per l'utente loggato"),
	

	TOOL_GENERICO(1800L,"1800 - Errore Generico sul tool"),
	TOOL_JAXB_CONTEXT(1801L,"1801 - problemi con il JaxbContext"),
	TOOL_MARSHALLER(1802L,"1802 - problemi con il JaxbContext"),
	TOOL_UNMARSHALLER(1803L,"1803 - problemi con il JaxbContext"),
	TOOL_BUILDER(1804L,"1804 - problemi con la creazione del Builder"),
	TOOL_FACTORY(1805L,"1805 - problemi con la creazione della Factory"),
	TOOL_URL(1806L,"1806 - url non valida"),
	
	SECURE_GENERIC(1900L,"1900 - Errore Generico sul tool di sicurezza"),
	SECURE_KEY_STORE(1901L,"1901 - problemi con il kaystore"),
	SECURE_ALIAS(1902L,"1902 - problemi con l'alias"),
	SECURE_ALIAS_NOT_FOUND(1903L,"1903 - alias non presente"),
	SECURE_KEY(1904L,"1904 - problemi con la chiave"),
	SECURE_KEY_NOT_FOUND(1905L,"1905 - key non presente"),
	SECURE_CERTIFICATE(1906L,"1906 - problemi con il certificato"),
	SECURE_CERTIFICATE_NOT_FOUND(1907L,"1907 - certificato non presente"),
	SECURE_FIRMA(1908L,"1908 - problemi durante la firma"),
	SECURE_VERIFICA_FIRMA(1909L,"1909 - problemi durante la verifica della firma"),
	SECURE_TRUST_STORE(1910L,"1910 - problemi con il truststore"),
	
	
	SOGEI_UPLOAD_LA_DATA_DI_INIZIO_VALIDITA_PUO_ESSERE_RETROATTIVA_AL_MASSIMO_DI_30_GIORNI(7044L,"7044 - LA DATA DI INIZIO VALIDITA’ PUO’ ESSERE RETROATTIVA AL MASSIMO DI 30 GIORNI"),
	SOGEI_UPLOAD_TITOLO_DEL_DICHIARANTE_INCOMPATIBILE_CON_IL_SOGGETTO_ESENTE(7045L,"7045 - TITOLO DEL DICHIARANTE INCOMPATIBILE CON IL SOGGETTO ESENTE"),
	SOGEI_UPLOAD_ERRORE_GENERICO(7050L,"7050 - ERRORE GENERICO"),
	SOGEI_UPLOAD_IL_CAMPO_USERID_E_ASSENTE(7060L,"7060 - IL CAMPO USERID E' ASSENTE"),
	SOGEI_UPLOAD_IL_CAMPO_CODICE_ESENZIONE_E_ASSENTE(7061L,"7061 - IL CAMPO CODICE ESENZIONE E' ASSENTE"),
	SOGEI_UPLOAD_IL_CAMPO_NOTE_E_ASSENTE(7062L,"7062 - IL CAMPO NOTE E' ASSENTE"),
	SOGEI_UPLOAD_IL_CAMPO_NOTE_NON_PUO_CONTENERE_PIU_DI_50_CARATTERI_7063(7063L,"7063 - IL CAMPO NOTE NON PUO' CONTENERE PIU' DI 50 CARATTERI"),
	SOGEI_UPLOAD_IL_CAMPO_TITOLO_DEL_DICHIARANTE_NON_E_PRESENTE(7064L,"7064 - IL CAMPO TITOLO DEL DICHIARANTE NON E' PRESENTE"),
	SOGEI_UPLOAD_IL_CAMPO_TITOLODICHIARANTE_NON_E_VALIDO(7065L,"7065 - IL CAMPO TITOLODICHIARANTE NON E' VALIDO"),
	SOGEI_UPLOAD_IL_CODICE_FISCALE_DEL_DICHIARANTE_DEVE_ESSERE_UGUALE_AL_CODICE_FISCALE_ASSISTITO_ESENTE(7066L,"7066 - IL CODICE FISCALE DEL DICHIARANTE DEVE ESSERE UGUALE AL CODICE FISCALE ASSISTITO ESENTE"),
	SOGEI_UPLOAD_CFDICHIARANTE_NON_PRESENTE(7067L,"7067 - CFDICHIARANTE NON PRESENTE"),
	SOGEI_UPLOAD_CFDICHIARANTE_NON_VALIDO(7068L,"7068 - CFDICHIARANTE NON VALIDO"),
	SOGEI_UPLOAD_CFDICHIARANTE_ERRATO(7069L,"7069 - CFDICHIARANTE ERRATO"),
	SOGEI_UPLOAD_CFTITOLARE_NON_PRESENTE(7070L,"7070 - CFTITOLARE NON PRESENTE"),
	SOGEI_UPLOAD_CFTITOLARE_NON_VALIDO(7071L,"7071 - CFTITOLARE NON VALIDO"),
	SOGEI_UPLOAD_CFTITOLARE_ERRATO(7072L,"7072 - CFTITOLARE ERRATO"),
	SOGEI_UPLOAD_CFASSISTITO_NON_PRESENTE(7073L,"7073 - CFASSISTITO NON PRESENTE"),
	SOGEI_UPLOAD_CFASSISTITO_NON_VALIDO(7074L,"7074 - CFASSISTITO NON VALIDO"),
	SOGEI_UPLOAD_CFASSISTITO_ERRATO(7075L,"7075 - CFASSISTITO ERRATO"),
	SOGEI_UPLOAD_DATAINIZIO_NON_PRESENTE(7076L,"7076 - DATAINIZIO NON PRESENTE"),
	SOGEI_UPLOAD_DATAINIZIO_ERRATA(7077L,"7077 - DATAINIZIO ERRATA"),
	SOGEI_UPLOAD_DATAFINE_NON_PRESENTE(7078L,"7078 - DATAFINE NON PRESENTE"),
	SOGEI_UPLOAD_DATAFINE_ERRATA(7079L,"7079 - DATAFINE ERRATA"),
	SOGEI_UPLOAD_DATAINIZIO_DOPO_DATAFINE(7080L,"7080 - DATAINIZIO DOPO DATAFINE"),
	SOGEI_UPLOAD_CFASSISTITO_DIVERSO_CFTITOLARE(7081L,"7081 - CFASSISTITO_DIVERSO_CFTITOLARE"),
	SOGEI_UPLOAD_IL_CAMPO_NOTE_NON_PUO_CONTENERE_PIU_DI_50_CARATTERI_7082(7082L,"7082 - IL CAMPO NOTE NON PUO' CONTENERE PIU' DI 50 CARATTERI"),
	SOGEI_UPLOAD_IL_CAMPO_NOTE_NON_PUO_CONTENERE_PIU_DI_50_CARATTERI_7083(7083L,"7083 - IL CAMPO NOTE NON PUO' CONTENERE PIU' DI 50 CARATTERI"),
	SOGEI_UPLOAD_IL_CAMPO_NOTE_NON_PUO_CONTENERE_PIU_DI_50_CARATTERI_7084(7084L,"7084 - IL CAMPO NOTE NON PUO' CONTENERE PIU' DI 50 CARATTERI"),
	SOGEI_UPLOAD_UTENTE_NON_RICONOSCIUTO(7085L,"7085 - UTENTE NON RICONOSCIUTO"),
	SOGEI_UPLOAD_UTENTE_NON_AUTORIZZATO(7086L,"7086 - UTENTE NON AUTORIZZATO"),
	SOGEI_UPLOAD_REGIONE_UTENTE_DIVERSA_DA_CERTIFICATO(7087L,"7087 - REGIONE UTENTE DIVERSA DA CERTIFICATO"),
	SOGEI_UPLOAD_CFDICHIARANTE_NON_PRESENTE_IN_ARCHIVIO(7088L,"7088 - CFDICHIARANTE NON PRESENTE IN ARCHIVIO"),
	SOGEI_UPLOAD_CODICECATASTALE_NON_PRESENTE(7089L,"7089 - CODICECATASTALE NON PRESENTE"),
	SOGEI_UPLOAD_CFTITOLARE_NON_PRESENTE_IN_ARCHIVIO(7090L,"7090 - CFTITOLARE NON PRESENTE IN ARCHIVIO"),
	SOGEI_UPLOAD_TOKEN_UTENTE_NON_PRESENTE(7091L,"7091 - TOKEN UTENTE NON PRESENTE"),
	SOGEI_UPLOAD_TOKEN_UTENTE_FORMALMENTE_ERRATO(7092L,"7092 - TOKEN UTENTE FORMALMENTE ERRATO"),
	SOGEI_UPLOAD_DATI_NON_PRESENTI(7093L,"7093 - DATI NON PRESENTI"),
	SOGEI_UPLOAD_CF_ASSISTITO_NON_PRESENTE_IN_ACHIVIO(7094L,"7094 - CF ASSISTITO NON PRESENTE IN ACHIVIO"),
	SOGEI_UPLOAD_ELABORAZIONE_CORRETTAMENTE_EFFETTUATA(7099L,"7099 - ELABORAZIONE CORRETTAMENTE EFFETTUATA"),

	SOGEI_REVOCA_ERRORE_GENERICO(7150L,"7150 - ERRORE GENERICO"),
	SOGEI_REVOCA_AUTOCERTIFICAZIONE_NON_TROVATA(7153L,"7153 - AUTOCERTIFICAZIONE NON TROVATA"),
	SOGEI_REVOCA_REGIONE_NON_ATTIVA(7155L,"7155 - REGIONE NON ATTIVA"),
	SOGEI_REVOCA_IL_CAMPO_USERID_E_ASSENTE(7160L,"7160 - IL CAMPO USERID E' ASSENTE"),
	SOGEI_REVOCA_IL_CAMPO_CODICE_ESENZIONE_E_ASSENTE(7161L,"7161 - IL CAMPO CODICE ESENZIONE E' ASSENTE"),
	SOGEI_REVOCA_IL_CAMPO_PROTOCOLLO_E_ASSENTE(7162L,"7162 - IL CAMPO PROTOCOLLO E' ASSENTE"),
	SOGEI_REVOCA_IL_CAMPO_ASSISITITO_NON_E_PRESENTE(7163L,"7163 - IL CAMPO ASSISITITO NON E' PRESENTE"),
	SOGEI_REVOCA_NESSUNA_AUTOCERTIFICAZIONE_VALIDA_DA_CHIUDERE(7171L,"7171 - NESSUNA AUTOCERTIFICAZIONE VALIDA DA CHIUDERE"),
	SOGEI_REVOCA_UTENTE_NON_RICONOSCIUTO(7185L,"7185 - UTENTE NON RICONOSCIUTO"),
	SOGEI_REVOCA_UTENTE_NON_AUTORIZZATO(7186L,"7186 - UTENTE NON AUTORIZZATO"),
	SOGEI_REVOCA_REGIONE_UTENTE_DIVERSA_DA_CERTIFICATO(7187L,"7187 - REGIONE UTENTE DIVERSA DA CERTIFICATO"),
	SOGEI_REVOCA_TOKEN_UTENTE_NON_PRESENTE(7191L,"7191 - TOKEN UTENTE NON PRESENTE"),
	SOGEI_REVOCA_TOKEN_UTENTE_FORMALMENTE_ERRATO(7192L,"7192 - TOKEN UTENTE FORMALMENTE ERRATO"),
	SOGEI_REVOCA_DATI_NON_PRESENTI(7193L,"7193 - DATI NON PRESENTI"),
	SOGEI_REVOCA_ELABORAZIONE_COMPLETATA_CORRETTAMENTE(7199L,"7199 - ELABORAZIONE COMPLETATA CORRETTAMENTE"),

	SOGEI_DOWNLOAD_IL_CAMPO_USERID_E_ASSENTE(7201L,"7201 - IL CAMPO USERID E' ASSENTE"),
	SOGEI_DOWNLOAD_IL_CAMPO_TOKEN_E_ASSENTE(7202L,"7202 - IL CAMPO TOKEN E' ASSENTE"),
	SOGEI_DOWNLOAD_IL_CAMPO_DATAORALIMITE_E_ASSENTE(7203L,"7203 - IL CAMPO DATAORALIMITE E' ASSENTE"),
	SOGEI_DOWNLOAD_IL_CAMPO_TIPOACCESSO_E_ASSENTE_7204(7204L,"7204 - IL CAMPO TIPOACCESSO E' ASSENTE"),
	SOGEI_DOWNLOAD_IL_CAMPO_DATAORALIMITE_DEVE_ESSERE_NEL_FORMATO_GGMMAAAAHH(7205L,"7205 - IL CAMPO DATAORALIMITE DEVE ESSERE NEL FORMATO GGMMAAAAHH"),
	SOGEI_DOWNLOAD_IL_CAMPO_DATAORALIMITE_DEVE_CONTENERE_SOLO_NUMERI(7206L,"7206 - IL CAMPO DATAORALIMITE DEVE CONTENERE SOLO NUMERI"),
	SOGEI_DOWNLOAD_IL_CAMPO_DATAORALIMITE_NON_PUO_ESSERE_SUCCESSIVO_ALLA_DATA_ODIERNA(7207L,"7207 - IL CAMPO DATAORALIMITE NON PUO' ESSERE SUCCESSIVO ALLA DATA ODIERNA"),
	SOGEI_DOWNLOAD_IL_CAMPO_USERID_E_FORMALMENTE_ERRATO(7208L,"7208 - IL CAMPO USERID E' FORMALMENTE ERRATO"),
	SOGEI_DOWNLOAD_IL_CAMPO_TIPOACCESSO_E_ASSENTE_7209(7209L,"7209 - IL CAMPO TIPOACCESSO E' ASSENTE"),
	SOGEI_DOWNLOAD_IL_CAMPO_TIPOACCESSO_DEVE_ESSERE_IMPOSTATO_CON_UNO_DEI_SEGUENTI_VALORI_I_V(7210L,"7210 - IL CAMPO TIPOACCESSO DEVE ESSERE IMPOSTATO CON UNO DEI SEGUENTI VALORI: I,V"),
	SOGEI_DOWNLOAD_UTENTE_NON_AUTORIZZATO(7211L,"7211 - UTENTE NON AUTORIZZATO"),
	SOGEI_DOWNLOAD_CODICE_FISCALE_NON_TROVATO(7212L,"7212 - CODICE FISCALE NON TROVATO"),
	SOGEI_DOWNLOAD_ERRORE_DB(7251L,"7251 - ERRORE DB"),
	SOGEI_DOWNLOAD_ELABORAZIONE_CORRETTAMENTE_EFFETTUATA(7299L,"7299 - ELABORAZIONE CORRETTAMENTE EFFETTUATA"),
	
	SOGEI_CERTIFICAZIONI_ERRORE_DI_SISTEMA(7350L, "7350 - ERRORE DI SISTEMA"),
	SOGEI_CERTIFICAZIONI_ERRORE_DI_SISTEMA2(7351L, "7351 - ERRORE DI SISTEMA"),
	SOGEI_CERTIFICAZIONI_DATI_NON_PRESENTI(7360L, "7360 - DATI NON PRESENTI"),
	SOGEI_CERTIFICAZIONI_CAMPO_USERID_ASSENTE(7361L, "7361 - CAMPO USERID E' ASSENTE"),
	SOGEI_CERTIFICAZIONI_CAMPO_TOKEN_ASSENTE(7362L, "7362 - CAMPO TOKEN NON PRESENTE"),
	SOGEI_CERTIFICAZIONI_TOKEN_FORMALMENTE_ERRATO(7363L, "7363 - TOKEN FORMALMENTE ERRATO"),
	SOGEI_CERTIFICAZIONI_CAMPO_DATA_NON_PRESENTE(7364L, "7364 - CAMPO DATA NON PRESENTE"),
	SOGEI_CERTIFICAZIONI_CAMPO_DATA_FORMALMENTE_ERRATO(7365L, "7365 - CAMPO DATA FORMALMENTE ERRATO, INSERIRE IL FORMATO GG/MM/AAAA"),
	SOGEI_CERTIFICAZIONI_DATA_FUTURA(7366L, "7366 - DATA FUTURA"),
	SOGEI_CERTIFICAZIONI_UTENTE_NON_RICONOSCIUTO(7385L, "7385 - UTENTE NON RICONOSCIUTO"),
	SOGEI_CERTIFICAZIONI_UTENTE_NON_AUTORIZZATO(7386L, "7386 - UTENTE NON AUTORIZZATO"),
	SOGEI_CERTIFICAZIONI_REGIONE_UTENTE_DIVERSA_DA_CERTIFICATO(7387L, "7387 - REGIONE UTENTE DIVERSA DA CERTIFICATO"),
	SOGEI_CERTIFICAZIONI_ASL_UTENTE_DIVERSA_DA_CERTIFICATO(7388L, "7388 - ASL UTENTE DIVERSA DA CERTIFICATO"),
	SOGEI_CERTIFICAZIONI_ELABORAZIONE_CORRETTAMENTE_EFFETTUATA(7399L, "7399 - ELABORAZIONE CORRETTAMENTE EFFETTUATA");
	
	public final long code;
	public final String msg;
	
	private Code(final long code, final String msg){
		this.code = code;
		this.msg = msg;
	}
	public static Code identifica(final long val) throws ConvertitoreException{
		for(Code c : values()){
			if(c.code == val){return c;}
		}
		throw new ConvertitoreException(Code.UNKNOWN_TYPE,"impossibile identificatr il codice ["+val+"]");
	}
	
	public static Code identifica(final Object val) throws ConvertitoreException{
		if(val != null){
			if(val instanceof Number){
				return identifica(((Number) val).longValue());
			} else if (val instanceof String){
				final String v = ((String)val).trim();
				if(v.length()<=4){
					try{
						return identifica((new Long(v)).longValue());
					} catch(Exception e) {
						throw new ConvertitoreException(Code.UNKNOWN_TYPE,"impossibile identificatr il codice ["+val+"]",e);
					}
				} else {
					return identifica(v.subSequence(0, 4));
				}
			} if (val instanceof Code){
				return (Code)val;
			}
			throw new ConvertitoreException(Code.UNKNOWN_TYPE,"impossibile identificatr il codice ["+val+"]");
		}
		throw new ConvertitoreException(Code.UNKNOWN_TYPE,"impossibile identificatr il codice nullo");
	}
	
}
