
SET SCHEMA ESENZIONIFASCE;


ALTER TABLE RICEVUTA_DOWNLOAD_SOGEI ADD NUMERO_RECORD_ELABORATI   BIGINT DEFAULT 0 NOT NULL ;
ALTER TABLE RICEVUTA_DOWNLOAD_SOGEI ADD NUMERO_RECORD_NUOVI       BIGINT DEFAULT 0 NOT NULL ;

--Da stabilire se devono essere rimovibili o meno le ricevutr delle esenzioni memorizzate
--ALTER TABLE DOWNLOAD_AUTOCERTIFICAZIONE DROP CONSTRAINT DOWNLOAD_AUTOCERTIFICAZIONE_RICEVUTA_DOWNLOAD_SOGEI;


CREATE TABLE AUTOCERTIFICAZIONE_TMP
(
   ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1  INCREMENT BY 1 NO CYCLE  NO CACHE),
   FK_RICEVUTA_DOWNLOAD_SOGEI BIGINT NOT NULL,
   RICEVUTA_INDEX BIGINT NOT NULL,
   NUMERO_ELABORAZIONI BIGINT DEFAULT 0 NOT NULL,
   DATA_ORDINAMENTO TIMESTAMP,

   ANNO_ESENZIONE CHAR(4),
   CODICE_ESENZIONE CHAR(3),
   FLAG_STATO CHAR(1),
   COD_ASL CHAR(3),
   DATA_AUTOCERTIFICAZIONE DATE,
   PROTOCOLLO VARCHAR(18),
   NOTE VARCHAR(512),
   DATA_INIZIO_VALID DATE,
   DATA_FINE_VALID DATE,
   DATA_FINE_VALID_OLD DATE,
   TITOLO CHAR(1),
   TIPO_AUTOCERTIFICAZIONE CHAR(1),

   CF_DICHIARANTE CHAR(16),
   COGNOME_DICHIARANTE VARCHAR(256),
   NOME_DICHIARANTE VARCHAR(256),
   DATA_NASCITA_DICHIARANTE DATE,
   SESSO_DICHIARANTE CHAR(1),
   COMUNE_NASCITA_DICHIARANTE VARCHAR(256),

   CF_TITOLARE CHAR(16),
   COGNOME_TITOLARE VARCHAR(256),
   NOME_TITOLARE VARCHAR(256),
   DATA_NASCITA_TITOLARE DATE,
   SESSO_TITOLARE CHAR(1),
   COMUNE_NASCITA_TITOLARE VARCHAR(256),

   CF_BENEFICIARIO CHAR(16),
   COGNOME_BENEFICIARIO VARCHAR(256),
   NOME_BENEFICIARIO VARCHAR(256),
   DATA_NASCITA_BENEFICIARIO DATE,
   SESSO_BENEFICIARIO CHAR(1),
   COMUNE_NASCITA_BENEFICIARIO VARCHAR(256),

   DATA_INSERIMENTO TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
   DATA_AGGIORNAMENTO TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL
)  IN TBS_ESENZIONIFA_N0 INDEX IN TBS_ESENZIONIFA_N0 COMPRESS YES;

ALTER TABLE AUTOCERTIFICAZIONE_TMP ADD PRIMARY KEY (ID);

CREATE INDEX FK_AT_RICEVUTA_DOWNLOAD_SOGEI ON AUTOCERTIFICAZIONE_TMP (FK_RICEVUTA_DOWNLOAD_SOGEI );


CREATE TABLE AUTOCERTIFICAZIONE_SCARTATE
(
   ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1  INCREMENT BY 1 NO CYCLE  NO CACHE),

   OLD_ID BIGINT NOT NULL,

   FK_RICEVUTA_DOWNLOAD_SOGEI BIGINT NOT NULL,
   RICEVUTA_INDEX BIGINT NOT NULL,
   NUMERO_ELABORAZIONI BIGINT DEFAULT 0 NOT NULL,
   DATA_ORDINAMENTO TIMESTAMP,

   ANNO_ESENZIONE CHAR(4),
   CODICE_ESENZIONE CHAR(3),
   FLAG_STATO CHAR(1),
   COD_ASL CHAR(3),
   DATA_AUTOCERTIFICAZIONE DATE,
   PROTOCOLLO VARCHAR(18),
   NOTE VARCHAR(512),
   DATA_INIZIO_VALID DATE,
   DATA_FINE_VALID DATE,
   DATA_FINE_VALID_OLD DATE,
   TITOLO CHAR(1),
   TIPO_AUTOCERTIFICAZIONE CHAR(1),

   CF_DICHIARANTE CHAR(16),
   COGNOME_DICHIARANTE VARCHAR(256),
   NOME_DICHIARANTE VARCHAR(256),
   DATA_NASCITA_DICHIARANTE DATE,
   SESSO_DICHIARANTE CHAR(1),
   COMUNE_NASCITA_DICHIARANTE VARCHAR(256),

   CF_TITOLARE CHAR(16),
   COGNOME_TITOLARE VARCHAR(256),
   NOME_TITOLARE VARCHAR(256),
   DATA_NASCITA_TITOLARE DATE,
   SESSO_TITOLARE CHAR(1),
   COMUNE_NASCITA_TITOLARE VARCHAR(256),

   CF_BENEFICIARIO CHAR(16),
   COGNOME_BENEFICIARIO VARCHAR(256),
   NOME_BENEFICIARIO VARCHAR(256),
   DATA_NASCITA_BENEFICIARIO DATE,
   SESSO_BENEFICIARIO CHAR(1),
   COMUNE_NASCITA_BENEFICIARIO VARCHAR(256),

   OLD_DATA_INSERIMENTO TIMESTAMP NOT NULL,
   OLD_DATA_AGGIORNAMENTO TIMESTAMP NOT NULL,

   DATA_INSERIMENTO TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
   DATA_AGGIORNAMENTO TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL

) IN TBS_ESENZIONIFA_N0 INDEX IN TBS_ESENZIONIFA_N0 COMPRESS YES;

ALTER TABLE AUTOCERTIFICAZIONE_SCARTATE ADD PRIMARY KEY (ID);





