SET SCHEMA ESENZIONIFASCE;

-- ESENZIONI_FASCE
ALTER TABLE ESENZIONI_FASCE ADD DATA_ULTIMA_VALUTAZIONE TIMESTAMP ;
ALTER TABLE ESENZIONI_FASCE ADD DATA_PROSSIMA_VALUTAZIONE DATE;
ALTER TABLE ESENZIONI_FASCE ADD FLAG_VALUTAZIONE integer NOT NULL DEFAULT 0 ;
	-- 0 mai valutato
	-- 1 storico in valutazione
	-- 2 valutato
	-- 3-8 altri impieghi
	-- 9 invalutabile

-- PROROGHE
ALTER TABLE PROROGHE ADD TIPO_ESENZIONE_DA_PROROGARE VARCHAR(3) ;
ALTER TABLE PROROGHE ADD MODALITA_PROROGAZIONE VARCHAR(256) ;
--RETTIFICATORE
--OPERATORE
