SET SCHEMA ESENZIONIFASCE;

INSERT INTO DECODIFICA_STATO_PROROGHE (CODE,DESCRIZIONE) values (5,'INSERITE_PER_LA_RETTIFICA');
INSERT INTO DECODIFICA_STATO_PROROGHE (CODE,DESCRIZIONE) values (200,'SCARTATE_PER_LA_RETTIFICA');

-- DECODIFICA_STATO_PROROGHE 
CREATE TABLE DECODIFICA_FLAG_VALUTAZIONE  (
		  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH +1 INCREMENT BY +1 MINVALUE +1  MAXVALUE +9223372036854775807 NO CYCLE ) , 
		  CODE BIGINT,
		  DESCRIZIONE VARCHAR(512)
) IN TBS_WSODS_N0 INDEX IN TBS_WSODS_N0 COMPRESS YES;


INSERT INTO DECODIFICA_FLAG_VALUTAZIONE (CODE,DESCRIZIONE) values (0,'DA_VALUTARE');
INSERT INTO DECODIFICA_FLAG_VALUTAZIONE (CODE,DESCRIZIONE) values (1,'VALUTATO_UN_ELEMENTO_DELLA_SUA_STORIA');
INSERT INTO DECODIFICA_FLAG_VALUTAZIONE (CODE,DESCRIZIONE) values (2,'VALUTATO_E_DA_RETTIFICARE_IN_SEGUITO');
INSERT INTO DECODIFICA_FLAG_VALUTAZIONE (CODE,DESCRIZIONE) values (3,'VALUTATO_E_DA_RETTIFICARE_INMEDIATAMENTE');
INSERT INTO DECODIFICA_FLAG_VALUTAZIONE (CODE,DESCRIZIONE) values (4,'RIVALUTATO');
INSERT INTO DECODIFICA_FLAG_VALUTAZIONE (CODE,DESCRIZIONE) values (9,'DA_NON_VALUTARE');

GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE DECODIFICA_FLAG_VALUTAZIONE TO USER yneng;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE DECODIFICA_FLAG_VALUTAZIONE TO USER esefasce;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE DECODIFICA_FLAG_VALUTAZIONE TO USER afeng;
