--2014.01.15.00.ESENZIONIFASCE.sql
--Gia' eseguito in precedenza

--2014.01.24.00.ESENZIONIFASCE.sql

SET SCHEMA ESENZIONIFASCE;


ALTER TABLE RICEVUTA_DOWNLOAD_SOGEI ADD NUMERO_RECORD_ELABORATI   BIGINT DEFAULT 0 NOT NULL ;
ALTER TABLE RICEVUTA_DOWNLOAD_SOGEI ADD NUMERO_RECORD_NUOVI       BIGINT DEFAULT 0 NOT NULL ;

--Da stabilire se devono essere rimovibili o meno le ricevutr delle esenzioni memorizzate
--ALTER TABLE DOWNLOAD_AUTOCERTIFICAZIONE DROP CONSTRAINT DOWNLOAD_AUTOCERTIFICAZIONE_RICEVUTA_DOWNLOAD_SOGEI;


CREATE TABLE AUTOCERTIFICAZIONE_TMP
(
   ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1  INCREMENT BY 1 NO CYCLE  NO CACHE),
   FK_RICEVUTA_DOWNLOAD_SOGEI BIGINT NOT NULL,
   RICEVUTA_INDEX BIGINT NOT NULL,
   NUMERO_ELABORAZIONI BIGINT DEFAULT 0 NOT NULL,
   DATA_ORDINAMENTO TIMESTAMP,

   ANNO_ESENZIONE CHAR(4),
   CODICE_ESENZIONE CHAR(3),
   FLAG_STATO CHAR(1),
   COD_ASL CHAR(3),
   DATA_AUTOCERTIFICAZIONE DATE,
   PROTOCOLLO VARCHAR(18),
   NOTE VARCHAR(512),
   DATA_INIZIO_VALID DATE,
   DATA_FINE_VALID DATE,
   DATA_FINE_VALID_OLD DATE,
   TITOLO CHAR(1),
   TIPO_AUTOCERTIFICAZIONE CHAR(1),

   CF_DICHIARANTE CHAR(16),
   COGNOME_DICHIARANTE VARCHAR(256),
   NOME_DICHIARANTE VARCHAR(256),
   DATA_NASCITA_DICHIARANTE DATE,
   SESSO_DICHIARANTE CHAR(1),
   COMUNE_NASCITA_DICHIARANTE VARCHAR(256),

   CF_TITOLARE CHAR(16),
   COGNOME_TITOLARE VARCHAR(256),
   NOME_TITOLARE VARCHAR(256),
   DATA_NASCITA_TITOLARE DATE,
   SESSO_TITOLARE CHAR(1),
   COMUNE_NASCITA_TITOLARE VARCHAR(256),

   CF_BENEFICIARIO CHAR(16),
   COGNOME_BENEFICIARIO VARCHAR(256),
   NOME_BENEFICIARIO VARCHAR(256),
   DATA_NASCITA_BENEFICIARIO DATE,
   SESSO_BENEFICIARIO CHAR(1),
   COMUNE_NASCITA_BENEFICIARIO VARCHAR(256),

   DATA_INSERIMENTO TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
   DATA_AGGIORNAMENTO TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL
)  IN TBS_ESENZIONIFA_N0 INDEX IN TBS_ESENZIONIFA_N0 COMPRESS YES;

ALTER TABLE AUTOCERTIFICAZIONE_TMP ADD PRIMARY KEY (ID);

CREATE INDEX FK_AT_RICEVUTA_DOWNLOAD_SOGEI ON AUTOCERTIFICAZIONE_TMP (FK_RICEVUTA_DOWNLOAD_SOGEI );


CREATE TABLE AUTOCERTIFICAZIONE_SCARTATE
(
   ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1  INCREMENT BY 1 NO CYCLE  NO CACHE),

   OLD_ID BIGINT NOT NULL,

   FK_RICEVUTA_DOWNLOAD_SOGEI BIGINT NOT NULL,
   RICEVUTA_INDEX BIGINT NOT NULL,
   NUMERO_ELABORAZIONI BIGINT DEFAULT 0 NOT NULL,
   DATA_ORDINAMENTO TIMESTAMP,

   ANNO_ESENZIONE CHAR(4),
   CODICE_ESENZIONE CHAR(3),
   FLAG_STATO CHAR(1),
   COD_ASL CHAR(3),
   DATA_AUTOCERTIFICAZIONE DATE,
   PROTOCOLLO VARCHAR(18),
   NOTE VARCHAR(512),
   DATA_INIZIO_VALID DATE,
   DATA_FINE_VALID DATE,
   DATA_FINE_VALID_OLD DATE,
   TITOLO CHAR(1),
   TIPO_AUTOCERTIFICAZIONE CHAR(1),

   CF_DICHIARANTE CHAR(16),
   COGNOME_DICHIARANTE VARCHAR(256),
   NOME_DICHIARANTE VARCHAR(256),
   DATA_NASCITA_DICHIARANTE DATE,
   SESSO_DICHIARANTE CHAR(1),
   COMUNE_NASCITA_DICHIARANTE VARCHAR(256),

   CF_TITOLARE CHAR(16),
   COGNOME_TITOLARE VARCHAR(256),
   NOME_TITOLARE VARCHAR(256),
   DATA_NASCITA_TITOLARE DATE,
   SESSO_TITOLARE CHAR(1),
   COMUNE_NASCITA_TITOLARE VARCHAR(256),

   CF_BENEFICIARIO CHAR(16),
   COGNOME_BENEFICIARIO VARCHAR(256),
   NOME_BENEFICIARIO VARCHAR(256),
   DATA_NASCITA_BENEFICIARIO DATE,
   SESSO_BENEFICIARIO CHAR(1),
   COMUNE_NASCITA_BENEFICIARIO VARCHAR(256),

   OLD_DATA_INSERIMENTO TIMESTAMP NOT NULL,
   OLD_DATA_AGGIORNAMENTO TIMESTAMP NOT NULL,

   DATA_INSERIMENTO TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
   DATA_AGGIORNAMENTO TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL

) IN TBS_ESENZIONIFA_N0 INDEX IN TBS_ESENZIONIFA_N0 COMPRESS YES;

ALTER TABLE AUTOCERTIFICAZIONE_SCARTATE ADD PRIMARY KEY (ID);





--2014.01.24.01.ESENZIONIFASCE.sql
SET SCHEMA ESENZIONIFASCE;

-- RICEVUTA_DOWNLOAD_SOGEI 
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE RICEVUTA_DOWNLOAD_SOGEI TO USER yneng;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE RICEVUTA_DOWNLOAD_SOGEI TO USER esefasce;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE RICEVUTA_DOWNLOAD_SOGEI TO USER afeng;

-- AUTOCERTIFICAZIONE_TMP 
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE AUTOCERTIFICAZIONE_TMP TO USER yneng;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE AUTOCERTIFICAZIONE_TMP TO USER esefasce;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE AUTOCERTIFICAZIONE_TMP TO USER afeng;

-- AUTOCERTIFICAZIONE_SCARTATE 
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE AUTOCERTIFICAZIONE_SCARTATE TO USER yneng;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE AUTOCERTIFICAZIONE_SCARTATE TO USER esefasce;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE AUTOCERTIFICAZIONE_SCARTATE TO USER afeng;



--2014.02.28.00.ESENZIONIFASCE.sql
SET SCHEMA ESENZIONIFASCE;

-- ESENZIONI_FASCE 
ALTER TABLE ESENZIONI_FASCE ADD SORGENTE VARCHAR (10) DEFAULT 'ALTRO' NOT NULL;

-- AUTOCERTIFICAZIONE_SCARTATE 
ALTER TABLE AUTOCERTIFICAZIONE_SCARTATE ADD SORGENTE VARCHAR (10);

-- AUTOCERTIFICAZIONE_TMP 
ALTER TABLE AUTOCERTIFICAZIONE_TMP ADD SORGENTE VARCHAR (10);



--2014.03.05.00.ESENZIONIFASCE.sql
SET SCHEMA ESENZIONIFASCE;

-- creazione tabella per il tracking

CREATE TABLE WSODS_SOAP_TRACKING (

    ID					BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1  INCREMENT BY 1  NO CYCLE  NO CACHE),

   	SRC					VARCHAR (26) NOT NULL, -- WSODS / APS_ESE / TOTEM / AUTOCERTIFICAZIONI-REDDITO
    DATA_REQUEST		TIMESTAMP,
    REQUEST				CLOB (536870912), -- 5 MB
    
    DEST				VARCHAR (7) NOT NULL, -- SOGEI / APS_ESE 
    DATA_RESPONSE		TIMESTAMP,
    RESPONSE			CLOB (1073741824), -- 10 MB
    
	ESITO				CHAR (2),	-- OK oppure KO
	STACK_TRACE			CLOB (2097152), -- 2 MB
	
	FK_LINK				BIGINT,
    
    DATA_INSERIMENTO	TIMESTAMP DEFAULT current timestamp NOT NULL,
    DATA_AGGIORNAMENTO	TIMESTAMP DEFAULT current timestamp NOT NULL


) IN TBS_ESENZIONIFA_N0 INDEX IN TBS_ESENZIONIFA_N0 COMPRESS YES;


GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE WSODS_SOAP_TRACKING TO USER yneng;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE WSODS_SOAP_TRACKING TO USER esefasce;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE WSODS_SOAP_TRACKING TO USER afeng;

