SET SCHEMA ESENZIONIFASCE;
-- PROROGHE 
ALTER TABLE PROROGHE ADD DATA_INIZIO_PROROGA 	DATE;
ALTER TABLE PROROGHE ADD ATTIVITA				CHAR(6) ; -- APRI/CHIUDI/ALTRO
ALTER TABLE PROROGHE ADD STATO					BIGINT DEFAULT 0 NOT NULL ;
ALTER TABLE PROROGHE ADD NUMERO_ELABORAZIONI	BIGINT DEFAULT 0 NOT NULL ;
ALTER TABLE PROROGHE ADD ESITO					CHAR(2);
ALTER TABLE PROROGHE ADD CODICE_ESITO			VARCHAR(4);
ALTER TABLE PROROGHE ADD DESCRIZIONE_ESITO		VARCHAR(512);
ALTER TABLE PROROGHE ADD FK_SOAP_TRACKING		BIGINT ;
ALTER TABLE PROROGHE ADD DATA_INSERIMENTO       TIMESTAMP DEFAULT current timestamp NOT NULL;
ALTER TABLE PROROGHE ADD DATA_AGGIORNAMENTO     TIMESTAMP DEFAULT current timestamp NOT NULL;


GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE PROROGHE TO USER yneng;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE PROROGHE TO USER esefasce;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE PROROGHE TO USER afeng;


-- AUTOCERTIFICAZIONE_SCARTATE 
ALTER TABLE AUTOCERTIFICAZIONE_SCARTATE ADD RIELABORA	BIGINT DEFAULT 0 NOT NULL ;
