SET SCHEMA ESENZIONIFASCE;


-- CREATE INDEX ON ESENZIONI_FASCE
CREATE INDEX IDX_ESE_FAS_RETT01 ON ESENZIONI_FASCE ( FLAG_TIPOLOGIA, TIPO_ESENZIONE, ID_UNIVERSALE_ASSISTITO ); -- RecuperoCERD e EsenzioniPerTipologia
CREATE INDEX IDX_ESE_FAS_RETT02 ON ESENZIONI_FASCE ( FLAG_TIPOLOGIA, TIPO_ESENZIONE, ID_UNIVERSALE_ASSISTITO, DATA_INIZIO ); --  storico Autocertificazione
CREATE INDEX IDX_ESE_FAS_RETT03 ON ESENZIONI_FASCE ( FLAG_TIPOLOGIA, TIPO_ESENZIONE, ID_UNIVERSALE_ASSISTITO, DATA_INIZIO, DATA_ORDINAMENTO, DATA_FORNITURA ); -- esiste Un esenzioneSuccessiva
CREATE INDEX IDX_ESE_FAS_RETT04 ON ESENZIONI_FASCE ( FLAG_TIPOLOGIA, TIPO_ESENZIONE, DATA_FINE, FLAG_VALUTAZIONE ); --  Esenzioni Da Valutare
CREATE INDEX IDX_ESE_FAS_RETT05 ON ESENZIONI_FASCE ( FLAG_TIPOLOGIA, TIPO_ESENZIONE, DATA_PROSSIMA_VALUTAZIONE ); --  Esenzioni Da Rettificare
CREATE INDEX IDX_ESE_FAS_RETT06 ON ESENZIONI_FASCE ( DATA_AGGIORNAMENTO); -- Ordinamento

-- CREATE INDEX ON PROROGHE
CREATE INDEX IDX_PROROGHE_RETT01 ON PROROGHE (STATO, ESENZIONI_FASCE_ID );  -- recupero proroghe generate dal rettificatore, pronte ad essere inviate 
CREATE INDEX IDX_PROROGHE_RETT02 ON PROROGHE ( DATA_AGGIORNAMENTO); -- Ordinamento
