SET SCHEMA ESENZIONIFASCE;

-- PROROGHE 
ALTER TABLE PROROGHE ADD TIPO_ESENZIONE							VARCHAR(3);
ALTER TABLE PROROGHE ADD ID_UNIVERSALE_ASSISTITO				VARCHAR(24);
ALTER TABLE PROROGHE ADD DATA_INIZIO_ESENZIONE_DA_PROREGARE 	DATE;
ALTER TABLE PROROGHE ADD DATA_FINE_ESENZIONE_DA_PROREGARE 		DATE;


-- DECODIFICA_STATO_PROROGHE 
CREATE TABLE DECODIFICA_STATO_PROROGHE  (
		  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH +1 INCREMENT BY +1 MINVALUE +1  MAXVALUE +9223372036854775807 NO CYCLE ) , 
		  CODE BIGINT,
		  DESCRIZIONE VARCHAR(32)
) IN TBS_WSODS_N0 INDEX IN TBS_WSODS_N0 COMPRESS YES;

ALTER TABLE DECODIFICA_STATO_PROROGHE  ADD PRIMARY KEY (ID);


GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE DECODIFICA_STATO_PROROGHE TO USER yneng;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE DECODIFICA_STATO_PROROGHE TO USER esefasce;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE DECODIFICA_STATO_PROROGHE TO USER afeng;

INSERT INTO DECODIFICA_STATO_PROROGHE (CODE,DESCRIZIONE) values (0,'NESSUN_OPERAZIONE');
INSERT INTO DECODIFICA_STATO_PROROGHE (CODE,DESCRIZIONE) values (10,'PRONTO_PER_LA_PROPAGAZIONE');
INSERT INTO DECODIFICA_STATO_PROROGHE (CODE,DESCRIZIONE) values (50,'IN_PROPAGAZIONE');
INSERT INTO DECODIFICA_STATO_PROROGHE (CODE,DESCRIZIONE) values (100,'PROPAGATO');
INSERT INTO DECODIFICA_STATO_PROROGHE (CODE,DESCRIZIONE) values (999,'IN_ERRORE');


