SET SCHEMA ESENZIONIFASCE;
-- RICEVUTA_DOWNLOAD_SOGEI 
ALTER TABLE RICEVUTA_DOWNLOAD_SOGEI ADD XML_DOCUMENT 		CLOB (1073741824); -- 10 MB
ALTER TABLE RICEVUTA_DOWNLOAD_SOGEI ADD STATO_ELABORAZIONE	BIGINT DEFAULT 2 NOT NULL ;
ALTER TABLE RICEVUTA_DOWNLOAD_SOGEI ADD PROTOCOLLO			VARCHAR(18);
