SET SCHEMA ESENZIONIFASCE;

-- PROROGHE
ALTER TABLE PROROGHE DROP TIPO_ESENZIONE_DA_PROROGARE;
ALTER TABLE PROROGHE ADD TIPO_ESENZIONE_GENERATA VARCHAR(3);
ALTER TABLE PROROGHE ADD ORDINE_DI_ESECUZIONE integer NOT NULL DEFAULT 0 ;

