SET SCHEMA ESENZIONIFASCE;



-- DROP TABLE IDUNI_DA_AGGIORNARE 
CREATE TABLE IDUNI_DA_AGGIORNARE  (
	ID 							BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH +1 INCREMENT BY +1 MINVALUE +1  MAXVALUE +9223372036854775807 NO CYCLE ) , 

	DATA_ULTIMO_AGGIORNAMENTO	TIMESTAMP NOT NULL,
	SLAVE						VARCHAR(24) NOT NULL,
	MASTER						VARCHAR(24) NOT NULL,
	STATO_UTILIZZO				BIGINT NOT NULL, 
	
	DATA_INSERIMENTO        	TIMESTAMP DEFAULT current timestamp NOT NULL,
	DATA_AGGIORNAMENTO      	TIMESTAMP DEFAULT current timestamp NOT NULL
) IN TBS_ESENZIONIFA_N0 INDEX IN TBS_ESENZIONIFA_N0 COMPRESS YES;

ALTER TABLE IDUNI_DA_AGGIORNARE ADD PRIMARY KEY (ID);


--  verifica duplicati
CREATE INDEX IDX_RIC_IDUNI_DA_AGGIORNARE_01 ON IDUNI_DA_AGGIORNARE ( DATA_ULTIMO_AGGIORNAMENTO, SLAVE, MASTER ); 


-- DROP TABLE TRACCIA_OBSOLESCENZA_ID_UNI 
CREATE TABLE TRACCIA_OBSOLESCENZA_ID_UNI  (
	ID 						BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH +1 INCREMENT BY +1 MINVALUE +1  MAXVALUE +9223372036854775807 NO CYCLE ) , 

	FK_IDUNI_DA_AGGIORNARE  BIGINT NOT NULL,
	FK_ESENZIONI_FASCE      BIGINT NOT NULL,
	RUOLO					VARCHAR(64) NOT NULL,
	
	DATA_INSERIMENTO        TIMESTAMP DEFAULT current timestamp NOT NULL,
	DATA_AGGIORNAMENTO      TIMESTAMP DEFAULT current timestamp NOT NULL
) IN TBS_ESENZIONIFA_N0 INDEX IN TBS_ESENZIONIFA_N0 COMPRESS YES;

ALTER TABLE TRACCIA_OBSOLESCENZA_ID_UNI ADD PRIMARY KEY (ID);

ALTER TABLE TRACCIA_OBSOLESCENZA_ID_UNI ADD CONSTRAINT TRACCIA_OBSOLESCENZA_ID_UNI_IDUNI_DA_AGGIORNARE FOREIGN KEY (FK_IDUNI_DA_AGGIORNARE) REFERENCES IDUNI_DA_AGGIORNARE (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE TRACCIA_OBSOLESCENZA_ID_UNI ADD CONSTRAINT TRACCIA_OBSOLESCENZA_ID_UNI_ESENZIONI_FASCE FOREIGN KEY (FK_ESENZIONI_FASCE) REFERENCES ESENZIONI_FASCE (ID) ON UPDATE NO ACTION ON DELETE NO ACTION;



-- DROP TABLE DECODIFICA_STATO_PROROGHE 
CREATE TABLE DECODIFICA_STATO_UTILIZZO  (
		  ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH +1 INCREMENT BY +1 MINVALUE +1  MAXVALUE +9223372036854775807 NO CYCLE ) , 
		  CODE BIGINT,
		  DESCRIZIONE VARCHAR(512)
) IN TBS_ESENZIONIFA_N0 INDEX IN TBS_ESENZIONIFA_N0 COMPRESS YES;

ALTER TABLE DECODIFICA_STATO_UTILIZZO ADD PRIMARY KEY (ID);

INSERT INTO DECODIFICA_STATO_UTILIZZO (CODE,DESCRIZIONE) values (0,'MAI_USATO');
INSERT INTO DECODIFICA_STATO_UTILIZZO (CODE,DESCRIZIONE) values (1,'RICERCATO_E_TROVATO');
INSERT INTO DECODIFICA_STATO_UTILIZZO (CODE,DESCRIZIONE) values (2,'RICERCATO_MA_NON_USATO');


GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE IDUNI_DA_AGGIORNARE TO USER yneng;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE IDUNI_DA_AGGIORNARE TO USER esefasce;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE IDUNI_DA_AGGIORNARE TO USER afeng;

GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE TRACCIA_OBSOLESCENZA_ID_UNI TO USER yneng;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE TRACCIA_OBSOLESCENZA_ID_UNI TO USER esefasce;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE TRACCIA_OBSOLESCENZA_ID_UNI TO USER afeng;
			
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE DECODIFICA_STATO_UTILIZZO TO USER yneng;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE DECODIFICA_STATO_UTILIZZO TO USER esefasce;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE DECODIFICA_STATO_UTILIZZO TO USER afeng;

GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE ESENZIONIFASCE_FLAT TO USER yneng;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE ESENZIONIFASCE_FLAT TO USER esefasce;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE ESENZIONIFASCE_FLAT TO USER afeng;


REORG TABLE ESENZIONIFASCE.ESENZIONI_FASCE;
REORG TABLE ESENZIONIFASCE.IDUNI_DA_AGGIORNARE;
REORG TABLE ESENZIONIFASCE.TRACCIA_OBSOLESCENZA_ID_UNI;
REORG TABLE ESENZIONIFASCE.DECODIFICA_STATO_UTILIZZO;
