SET SCHEMA ESENZIONIFASCE;


--DROP TABLE AUTOCERTIFICAZIONE_APERTURE_ETL;
--DROP TABLE AUTOCERTIFICAZIONE_CHIUSURE_ETL;
--DROP TABLE ESITO_INVIO_APERTURE_ETL;
--DROP TABLE ESITO_INVIO_CHIUSURE_ETL;

CREATE TABLE AUTOCERTIFICAZIONE_APERTURE_ETL
(
   ID								BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1  INCREMENT BY 1 NO CYCLE  NO CACHE),
   FK_ESENZIONE_PROROGATA			BIGINT NOT NULL,
   STATO_ELABORAZIONE				BIGINT DEFAULT 0 NOT NULL,
   
   CODICE_ESENZIONE					CHAR(3) NOT NULL,
   ID_UNI_BENEFICIARIO				CHAR(24) NOT NULL,
   ID_UNI_DICHIARANTE				CHAR(24) NOT NULL,
   ID_UNI_TITOLARE					CHAR(24) NOT NULL,
   TITOLO							CHAR(1) NOT NULL,
   
   DATA_FINE						DATE NOT NULL,

   DATA_INVIO						DATE,
   NUMERO_ELABORAZIONI				BIGINT DEFAULT 0 NOT NULL,
   
   DATA_INSERIMENTO					TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
   DATA_AGGIORNAMENTO				TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL
)  IN TBS_ESENZIONIFA_N0 INDEX IN TBS_ESENZIONIFA_N0 COMPRESS YES;

ALTER TABLE AUTOCERTIFICAZIONE_APERTURE_ETL ADD PRIMARY KEY (ID);

CREATE INDEX NDX_AUTOCERTIFICAZIONE_APERTURE_ETL_000 ON AUTOCERTIFICAZIONE_APERTURE_ETL (ID,STATO_ELABORAZIONE,NUMERO_ELABORAZIONI );
CREATE INDEX NDX_AUTOCERTIFICAZIONE_APERTURE_ETL_001 ON AUTOCERTIFICAZIONE_APERTURE_ETL (STATO_ELABORAZIONE,DATA_AGGIORNAMENTO );


CREATE TABLE AUTOCERTIFICAZIONE_CHIUSURE_ETL
(
   ID								BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1  INCREMENT BY 1 NO CYCLE  NO CACHE),
   FK_ESENZIONE_PROROGATA			BIGINT NOT NULL,
   STATO_ELABORAZIONE				BIGINT DEFAULT 0 NOT NULL,
   
   CODICE_ESENZIONE					CHAR(3) NOT NULL,
   ID_UNI_BENEFICIARIO				CHAR(24) NOT NULL,
   ID_UNI_DICHIARANTE				CHAR(24) NOT NULL,
   ID_UNI_TITOLARE					CHAR(24) NOT NULL,
   TITOLO							CHAR(1) NOT NULL,
   
   PROTOCOLLO						VARCHAR(18) NOT NULL,
   DATA_INIZIO						DATE NOT NULL,
   DATA_FINE_OLD					DATE NOT NULL,
   

   DATA_INVIO						DATE ,
   NUMERO_ELABORAZIONI				BIGINT DEFAULT 0 NOT NULL,
   
   DATA_INSERIMENTO					TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
   DATA_AGGIORNAMENTO				TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL
)  IN TBS_ESENZIONIFA_N0 INDEX IN TBS_ESENZIONIFA_N0 COMPRESS YES;

ALTER TABLE AUTOCERTIFICAZIONE_CHIUSURE_ETL ADD PRIMARY KEY (ID);


CREATE INDEX NDX_AUTOCERTIFICAZIONE_CHIUSURE_ETL_000 ON AUTOCERTIFICAZIONE_CHIUSURE_ETL (ID,STATO_ELABORAZIONE,NUMERO_ELABORAZIONI );
CREATE INDEX NDX_AUTOCERTIFICAZIONE_CHIUSURE_ETL_001 ON AUTOCERTIFICAZIONE_CHIUSURE_ETL (STATO_ELABORAZIONE,DATA_AGGIORNAMENTO );

CREATE TABLE ESITO_INVIO_APERTURE_ETL
(
	ID									BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1  INCREMENT BY 1 NO CYCLE  NO CACHE),
	FK_AUTOCERTIFICAZIONE_ETL			BIGINT NOT NULL,
	FK_WSODS_SOAP_TRACKING				BIGINT NOT NULL, -- 0 se non c'e tracciatura
 
	ESITO								CHAR (2),	-- OK oppure KO
	ESITO_COD							VARCHAR (16),	-- codice esito
	ESITO_DESC							VARCHAR (512),	-- descrizione esito
	STACK_TRACE							CLOB (2097152), -- 2 MB
   
	DATA_INSERIMENTO					TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
	DATA_AGGIORNAMENTO					TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL
)  IN TBS_ESENZIONIFA_N0 INDEX IN TBS_ESENZIONIFA_N0 COMPRESS YES;

ALTER TABLE ESITO_INVIO_APERTURE_ETL ADD PRIMARY KEY (ID);


CREATE TABLE ESITO_INVIO_CHIUSURE_ETL
(
	ID									BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1  INCREMENT BY 1 NO CYCLE  NO CACHE),
	FK_AUTOCERTIFICAZIONE_ETL			BIGINT NOT NULL,
	FK_WSODS_SOAP_TRACKING				BIGINT NOT NULL, -- 0 se non c'e tracciatura
    
	ESITO								CHAR (2),	-- OK oppure KO
	ESITO_COD							VARCHAR (16),	-- codice esito
	ESITO_DESC							VARCHAR (512),	-- descrizione esito
	STACK_TRACE							CLOB (2097152), -- 2 MB
   
   DATA_INSERIMENTO						TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
   DATA_AGGIORNAMENTO					TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL
)  IN TBS_ESENZIONIFA_N0 INDEX IN TBS_ESENZIONIFA_N0 COMPRESS YES;

ALTER TABLE ESITO_INVIO_CHIUSURE_ETL ADD PRIMARY KEY (ID);



GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE AUTOCERTIFICAZIONE_APERTURE_ETL TO USER yneng;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE AUTOCERTIFICAZIONE_APERTURE_ETL TO USER esefasce;

GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE AUTOCERTIFICAZIONE_CHIUSURE_ETL TO USER yneng;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE AUTOCERTIFICAZIONE_CHIUSURE_ETL TO USER esefasce;

GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE ESITO_INVIO_APERTURE_ETL TO USER yneng;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE ESITO_INVIO_APERTURE_ETL TO USER esefasce;

GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE ESITO_INVIO_CHIUSURE_ETL TO USER yneng;
GRANT INSERT, SELECT, UPDATE, DELETE, INDEX  ON TABLE ESITO_INVIO_CHIUSURE_ETL TO USER esefasce;



