SET SCHEMA ESENZIONIFASCE;



CREATE INDEX NDX_ESENZIONI_FASCE_000 ON ESENZIONI_FASCE ( TITOLO, PROTOCOLLO );
CREATE INDEX NDX_ESENZIONI_FASCE_001 ON ESENZIONI_FASCE ( DATA_INIZIO );


CREATE INDEX NDX_AUTOCERTIFICAZIONE_SCARTATE_000 ON AUTOCERTIFICAZIONE_SCARTATE (ID,TITOLO,NUMERO_ELABORAZIONI,RIELABORA );
CREATE INDEX NDX_AUTOCERTIFICAZIONE_SCARTATE_001 ON AUTOCERTIFICAZIONE_SCARTATE (DATA_AGGIORNAMENTO );



