
SET CURRENT SCHEMA ESENZIONIFASCE;

CREATE INDEX FK_DA_TR_OBS_IDUNI_TO_ID_DA_AGG ON TRACCIA_OBSOLESCENZA_ID_UNI (FK_IDUNI_DA_AGGIORNARE);

CREATE INDEX FK_DA_TR_OBS_IDUNI_TO_ESEFASCE ON TRACCIA_OBSOLESCENZA_ID_UNI (FK_ESENZIONI_FASCE);