
DROP TRIGGER ESENZIONIFASCE.IDUNI_DA_AGGIORNARE_UPD_TRG;
CREATE TRIGGER ESENZIONIFASCE.IDUNI_DA_AGGIORNARE_UPD_TRG
  AFTER UPDATE OF STATO_UTILIZZO ON ESENZIONIFASCE.IDUNI_DA_AGGIORNARE 
  REFERENCING NEW AS ROWREC
	FOR EACH ROW WHEN (ROWREC.STATO_UTILIZZO = 1)
	BEGIN ATOMIC

		FOR ESECURSOR AS 
				
			SELECT 
				E.TIPO_ESENZIONE,E.FLAG_TIPOLOGIA,E.DATA_INIZIO,T.FK_ESENZIONI_FASCE,T.RUOLO
			FROM 
				ESENZIONIFASCE.TRACCIA_OBSOLESCENZA_ID_UNI T,
				ESENZIONIFASCE.ESENZIONI_FASCE E
			WHERE 
				T.FK_IDUNI_DA_AGGIORNARE = ROWREC.ID
			AND E.ID = T.FK_ESENZIONI_FASCE 
			ORDER BY  T.ID
		
		DO

			IF ESECURSOR.RUOLO = 'BENEFICIARIO' THEN
			
				IF ESECURSOR.FLAG_TIPOLOGIA IS NULL THEN
					DELETE FROM 
						ESENZIONIFASCE.ESENZIONIFASCE_FLAT 
					WHERE 
						( ID_UNIVERSALE_ASSISTITO = ROWREC.SLAVE OR	ID_UNIVERSALE_ASSISTITO = ROWREC.MASTER )
					AND TIPO_ESENZIONE = ESECURSOR.TIPO_ESENZIONE
					AND DATA_INIZIO = ESECURSOR.DATA_INIZIO
					AND FLAG_TIPOLOGIA IS NULL;--
				ELSE
					DELETE FROM 
						ESENZIONIFASCE.ESENZIONIFASCE_FLAT 
					WHERE 
						( ID_UNIVERSALE_ASSISTITO = ROWREC.SLAVE OR	ID_UNIVERSALE_ASSISTITO = ROWREC.MASTER )
					AND TIPO_ESENZIONE = ESECURSOR.TIPO_ESENZIONE
					AND DATA_INIZIO = ESECURSOR.DATA_INIZIO
					AND FLAG_TIPOLOGIA = ESECURSOR.FLAG_TIPOLOGIA;--
				END IF;--

-- update che innesca il trigger di consolidamento
				UPDATE 
					ESENZIONIFASCE.ESENZIONI_FASCE
				SET
					AVVIATRG = 'Z'
				WHERE
					ID = ESECURSOR.FK_ESENZIONI_FASCE;--


			END IF;--

			IF ESECURSOR.RUOLO = 'DICHIARANTE' THEN

				UPDATE
					ESENZIONIFASCE.ESENZIONIFASCE_FLAT 
				SET 
					ID_UNI_DICHIARANTE = ROWREC.MASTER
				WHERE 
					ID_UNI_DICHIARANTE = ROWREC.SLAVE ;--

			END IF;--

			IF ESECURSOR.RUOLO = 'TITOLARE' THEN

				UPDATE
					ESENZIONIFASCE.ESENZIONIFASCE_FLAT 
				SET 
					ID_UNI_TITOLARE = ROWREC.MASTER
				WHERE 
					ID_UNI_TITOLARE = ROWREC.SLAVE ;--

			END IF;--

		END FOR;--
END;
